image: registry.gitlab.com/thehat/expression-ts:latest

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules/

stages:
- build
- test

build:
    stage: build
    script:
        - npm install -g tsd typescript webpack
        - npm install
        - tsd install
        - tsc
        - npm link typescript
        - webpack
        - webpack --config=webpack.test.config.js
    artifacts:
        paths:
            - js/

test:
    stage: test
    script:
        - npm install
        - npm test
